repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: nats
    url: https://nats-io.github.io/k8s/helm/charts

releases:
  - name: postgres
    namespace: kais-system
    chart: bitnami/postgresql
    values:
      - auth:
          postgresPassword: kais
          database: kais
        primary:
          initdb:
            scripts:
              init.sql: |
                CREATE TABLE IF NOT EXISTS cell_events (
                    id BIGSERIAL PRIMARY KEY,
                    cell_name TEXT NOT NULL,
                    namespace TEXT NOT NULL,
                    event_type TEXT NOT NULL,
                    payload JSONB NOT NULL,
                    created_at TIMESTAMPTZ DEFAULT NOW()
                );
                CREATE INDEX IF NOT EXISTS idx_cell_events_cell ON cell_events(namespace, cell_name);
                CREATE INDEX IF NOT EXISTS idx_cell_events_type ON cell_events(event_type);
                CREATE INDEX IF NOT EXISTS idx_cell_events_created ON cell_events(created_at);
          persistence:
            size: 5Gi
          resources:
            requests: { memory: 256Mi, cpu: 250m }
            limits: { memory: 512Mi, cpu: 500m }

  - name: nats
    namespace: kais-system
    chart: nats/nats
    values:
      - nats:
          jetstream:
            enabled: true
            memStorage:
              enabled: true
              size: 256Mi
            fileStorage:
              enabled: true
              size: 1Gi
        cluster:
          enabled: false   # single node for minikube

  - name: ollama
    namespace: kais-system
    chart: ./helm/kais-infra/charts/ollama
    condition: ollama.enabled
