# Formation: custom topology with explicit routing
# Define exactly which cells can communicate with which.
# Useful for complex workflows with specific data flow requirements.
apiVersion: kais.io/v1
kind: Formation
metadata:
  name: data-pipeline
  namespace: demo
spec:
  cells:
    - name: ingester
      replicas: 1
      spec:
        mind:
          provider: ollama
          model: qwen2.5:7b
          systemPrompt: |
            You ingest raw data, clean it, and forward to processors.
          temperature: 0
        tools:
          - name: send_message
          - name: read_file

    - name: processor
      replicas: 2
      spec:
        mind:
          provider: ollama
          model: qwen2.5:7b
          systemPrompt: |
            You process cleaned data and forward results to the aggregator.
          temperature: 0
        tools:
          - name: send_message
          - name: bash

    - name: aggregator
      replicas: 1
      spec:
        mind:
          provider: anthropic
          model: claude-sonnet-4-20250514
          systemPrompt: |
            You aggregate processed results into a final report
            and write it to /workspace/report.md.
          temperature: 0.2
        tools:
          - name: send_message
          - name: write_file

  topology:
    type: custom
    routes:
      - from: ingester
        to: [processor]
      - from: processor
        to: [aggregator]
    broadcast:
      enabled: true
      from: [aggregator]

  budget:
    maxTotalCost: 2.00
