# Formation: hierarchy topology
# A tree structure where the director delegates to team leads,
# who in turn coordinate their own workers.
apiVersion: kais.io/v1
kind: Formation
metadata:
  name: engineering-org
  namespace: demo
spec:
  cells:
    - name: director
      replicas: 1
      spec:
        mind:
          provider: anthropic
          model: claude-sonnet-4-20250514
          systemPrompt: |
            You are the engineering director. Break down large projects
            into team-level tasks and delegate to team leads.
          temperature: 0.2
        tools:
          - name: send_message
          - name: write_file

    - name: backend-lead
      replicas: 1
      spec:
        mind:
          provider: anthropic
          model: claude-sonnet-4-20250514
          systemPrompt: |
            You are the backend team lead. Receive tasks from the director
            and coordinate backend workers to implement them.
          temperature: 0.3
        tools:
          - name: send_message
          - name: write_file
          - name: bash

    - name: frontend-lead
      replicas: 1
      spec:
        mind:
          provider: openai
          model: gpt-4o
          systemPrompt: |
            You are the frontend team lead. Receive tasks from the director
            and coordinate frontend workers to implement them.
          temperature: 0.3
        tools:
          - name: send_message
          - name: write_file

    - name: backend-worker
      replicas: 2
      spec:
        mind:
          provider: ollama
          model: qwen2.5:7b
          systemPrompt: You are a backend developer. Write code as assigned.
          temperature: 0.1
        tools:
          - name: write_file
          - name: bash
          - name: send_message
        resources:
          maxTokensPerTurn: 4096
          memoryLimit: 512Mi

    - name: frontend-worker
      replicas: 2
      spec:
        mind:
          provider: ollama
          model: qwen2.5:7b
          systemPrompt: You are a frontend developer. Write code as assigned.
          temperature: 0.1
        tools:
          - name: write_file
          - name: send_message
        resources:
          maxTokensPerTurn: 4096
          memoryLimit: 512Mi

  topology:
    type: hierarchy
    root: director

  budget:
    maxTotalCost: 10.00
