# Formation: stigmergy topology (blackboard pattern)
# Cells communicate through a shared blackboard — no direct messaging.
# Each cell reads from and writes to the shared state, enabling
# emergent coordination without explicit routing.
apiVersion: kais.io/v1
kind: Formation
metadata:
  name: bug-hunters
  namespace: demo
spec:
  cells:
    - name: scanner
      replicas: 3
      spec:
        mind:
          provider: ollama
          model: qwen2.5:7b
          systemPrompt: |
            You are a bug scanner. Read source files from the workspace,
            look for bugs and vulnerabilities, and write your findings
            to the shared blackboard. Check the blackboard first to
            avoid duplicating work others have already done.
          temperature: 0.2
        tools:
          - name: read_file
          - name: write_file
          - name: bash
        resources:
          maxTokensPerTurn: 4096
          memoryLimit: 512Mi

    - name: fixer
      replicas: 2
      spec:
        mind:
          provider: ollama
          model: qwen2.5:7b
          systemPrompt: |
            You are a bug fixer. Read bug reports from the blackboard
            and implement fixes. Mark bugs as fixed on the blackboard
            when done.
          temperature: 0.1
        tools:
          - name: read_file
          - name: write_file
          - name: bash
        resources:
          maxTokensPerTurn: 4096
          memoryLimit: 512Mi

  topology:
    type: stigmergy
    blackboard:
      decayMinutes: 60

  budget:
    maxTotalCost: 0
    maxCostPerHour: 0
